apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: training-db
  name: training-db
  namespace: myapps
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: training-db
  template:
    metadata:
      labels:
        app: training-db
    spec:
      containers:
      - image: gcr.io/ringed-tuner-289209/trainingdbapi:0.0.1 # Docker image name, that we pushed to GCR
        name: training-db-api     # POD name
        volumeMounts:
        - mountPath: /usr/src/tdb
          name: training-db-vol
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_LOC
          value: /usr/src/tdb/
      volumes:
      - name: training-db-vol
        persistentVolumeClaim:
          claimName: nfs-data